name = "GerryChain"
uuid = "e09a5c58-8952-4b57-bc02-56d902e45e6e"
authors = ["Metric Geometry and Gerrymandering Group <contact@mggg.org>"]
version = "0.1.3"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LibSpatialIndex = "f19c2e90-9d16-5f2d-a2a7-af3fb29e4907"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataStructures = "0.17.9"
Documenter = "0.25.2"
DocumenterTools = "0.1.7"
HDF5 = "0.15.4"
JSON = "0.21.0"
LibGEOS = "0.6.5"
LibSpatialIndex = "0.2.0"
LightGraphs = "1.3.0"
PyPlot = "2.9.0"
Shapefile = "0.6.2"
julia = "1.3.1"
